name: Deploy Web App to S3 + Cloudfront

on:
  push:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build web App
        run: mvn clean package

      - name: Upload static files to S3
        uses: jakejarvis/s3-sync-action@v0.4.0
        with:
          source-dir: WebContent/
          bucket: ${{ secrets.s3_bucket }}
          region: ${{ secrets.region }}
          delete: true

      - name: Invalidate Cloudfront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          distribution-id: ${{ secrets.cloudfront }}
          paths: "/*"
          aws_region: ${{ secrets.aws_region }}