name: Deploy Web App to S3 + Cloudfront.

on:
  push:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build web App
        run: mvn clean package

      - name: Upload static files to S3
        uses: jakejarvis/s3-sync-action@v0.4.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.s3_bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret }}
          AWS_REGION: ${{ secrets.aws_region }}
          SOURCE_DIR: WebContent/

      - name: Invalidate Cloudfront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.cloudfront }}
          PATHS: "/*"
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret }}
          AWS_REGION: ${{ secrets.aws_region }}